version: '3.8'

services:
  # База данных для разработки
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-swapsphere_dev}
      POSTGRES_USER: ${POSTGRES_USER:-dev_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-dev_user}"]
      interval: 30s
      timeout: 10s
      retries: 3
  # Веб-приложение для разработки (обновлено)
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=development
    restart: unless-stopped
    volumes:
      - .:/app
      - media_dev_files:/app/media
    ports:
      - "${WEB_PORT:-8000}:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-not-for-production}
      - DATABASE_URL=postgres://${POSTGRES_USER:-dev_user}:${POSTGRES_PASSWORD:-dev_password}@db:5432/${POSTGRES_DB:-swapsphere_dev}
      - DJANGO_SETTINGS_MODULE=swapsphere.settings
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,${CUSTOM_HOST:-}
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
             
  # Добавлен Redis для разработки
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --appendonly yes

volumes:
  postgres_dev_data:
    driver: local
  media_dev_files:
    driver: local

# Добавлены инструменты для разработки
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "${MAILHOG_PORT:-8025}:8025"
      - "1025:1025"
    logging:
      driver: 'none'
      
  # Опциональный PgAdmin для разработчиков
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@swapsphere.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db
