version: '3.8'

services:
  # База данных для разработки
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: swapsphere_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Веб-приложение для разработки
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
      - media_dev_files:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=dev-secret-key-not-for-production
      - DATABASE_URL=postgres://dev_user:dev_password@db:5432/swapsphere_dev
      - DJANGO_SETTINGS_MODULE=swapsphere.settings
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_dev_data:
    driver: local
  media_dev_files:
    driver: local
