# Generated by Django 4.2.21 on 2025-06-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('in_exchange', 'В обмене'), ('exchanged', 'Обменен')], default='available', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], default='pending', max_length=50, verbose_name='Статус'),
        ),
    ]
